<a href="https://colab.research.google.com/github/ananya0504/MLproject/blob/main/myFirstMLproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [4]:
from sklearn.datasets import load_iris #sklearn is the framework, datasets is the module and load_iris is the function
iris_dataset = load_iris()

In [5]:
print("Keys of iris_dataset are : \n{}".format(iris_dataset.keys()) )

Keys of iris_dataset are : 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [6]:
val = iris_dataset['DESCR']
start_val= val[:200]
print(start_val + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
...


In [11]:
print("Target names : {}".format(iris_dataset['target_names']) ) #the species of flowers we want to predict

Target names : ['setosa' 'versicolor' 'virginica']


In [12]:
print("Feature names : {}".format(iris_dataset['feature_names']) ) #the description of each feature of a flower

Feature names : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [13]:
print("Type of data : {}".format(type(iris_dataset['data']))) #the type in which we recieve data

Type of data : <class 'numpy.ndarray'>


In [18]:
print("Shape of data : {}".format(iris_dataset['data'].shape)) #the rows represnt 150 flowers while the columns represent the 4 feature measurements
#Individual items are called samples or data points and their properties are called features
#shape is the number of samples multiplied by the number of features

Shape of data : (150, 4)


In [22]:
print("First five columns of data : \n{}".format(iris_dataset['data'][:5]))  # we observe that the all the flowers have the same petal width and the 
# first flower has the max sepal width

First five columns of data : 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [21]:
print("Type of Target : {}".format(type(iris_dataset['target']))) #the type in which we recieve the target

Type of Target : <class 'numpy.ndarray'>


In [23]:
print("Shape of Target : {}".format(iris_dataset['target'].shape)) #we see that is has one entry per flower

Shape of Target : (150,)


In [24]:
print("Target : {}".format(iris_dataset['target'])) #we see that the species are encoded as digits between 0-2
#0-sentose 1-versicolor 2-virginica

Target : [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
